# Generated by Django 3.1.1 on 2020-09-18 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_auto_20200918_0905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='price',
            field=models.DecimalField(decimal_places=2, default='item.price', max_digits=5),
        ),
    ]
