# Generated by Django 3.1.1 on 2020-09-18 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_auto_20200918_0913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='price',
            field=models.DecimalField(decimal_places=2, default=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.pizza'), max_digits=5),
        ),
    ]
