# Generated by Django 3.1.1 on 2020-09-22 03:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_auto_20200921_1535'),
    ]

    operations = [
        migrations.CreateModel(
            name='PizzaOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('style', models.CharField(max_length=64)),
                ('size', models.CharField(max_length=64)),
                ('toppings', models.CharField(max_length=64)),
                ('topping_1', models.CharField(max_length=64)),
                ('topping_2', models.CharField(max_length=64)),
                ('topping_3', models.CharField(max_length=64)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.RemoveField(
            model_name='cart',
            name='order',
        ),
        migrations.AddField(
            model_name='cart',
            name='pizza_order',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='orders.pizzaorder'),
            preserve_default=False,
        ),
    ]
