# Generated by Django 3.1.1 on 2020-09-22 03:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_pizzaorder_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizzaorder',
            name='style',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.pizza'),
        ),
    ]
