# Generated by Django 3.1.1 on 2020-09-22 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_auto_20200921_2135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizzaorder',
            name='style',
            field=models.CharField(max_length=64),
        ),
    ]
