# Generated by Django 3.1.1 on 2020-09-22 15:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0019_remove_cart_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cart',
            name='pizza_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_order', to='orders.pizzaorder'),
        ),
    ]
