# Generated by Django 3.1.1 on 2020-09-22 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0021_suborder'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizzaorder',
            name='extra_1',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AddField(
            model_name='pizzaorder',
            name='extra_2',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AddField(
            model_name='pizzaorder',
            name='extra_3',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AddField(
            model_name='pizzaorder',
            name='extra_4',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.DeleteModel(
            name='SubOrder',
        ),
    ]
