# Generated by Django 3.1.1 on 2020-09-23 02:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0029_auto_20200922_2003'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='complete',
        ),
    ]
