# Generated by Django 3.1.1 on 2020-09-23 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0030_remove_order_complete'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='user',
            new_name='customer',
        ),
    ]
