# Generated by Django 3.1.1 on 2020-09-23 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0031_auto_20200923_1035'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='customer',
            new_name='user',
        ),
    ]
